### ISSUE TITLE
The  attribute  fontsize  in  legend  can not  execute.

### ISSUE THREAD

**Issue by whpldgs** [proplot-dev/proplot#383] opened 2022-08-15 14:25 UTC
### Description
When  set  fontsize=300 in legend, the  attribute  fontsize  in  legend  can not  execute,  the  legned  fontsize unchanged.

```python
import proplot as pplt

labels = ['a', 'bb', 'ccc', 'ddddd', 'eeeee']

fig, axs = pplt.subplots(ncols=2, share=False, axwidth=3)
hs1, hs2 = [], []

state = np.random.RandomState(51423)
for i,label in enumerate(labels):
    data = (state.rand(20) - 0.45).cumsum(axis=0)
    h1 = axs[0].plot(data, lw=4, label=label, legend='ul',
                     legend_kw={'order':'F', 'title':'column major'})
    hs1.extend(h1)
    h2 = axs[1].plot(data, lw=4, label=label, legend='r', cycle='Set3', 
                     legend_kw={'ncols':1, 'order':'F', 'frame':False, 'title':'No Frame', 'fontsize':40})
    hs2.extend(h2)

# Outer legends
axs[0].legend(loc='b', ncols=3, facecolor='red', fontsize=300)

```
![图片](https://user-images.githubusercontent.com/37328100/184653249-6ea4f258-7ce2-4d53-a442-8aea330ed44a.png)

**Comment by AWSisco** [comment] 2022-08-15 15:45
This might be a duplicate of #331, which was resolved. If you are using an older version of proplot, it might be worth updating to the latest development version to see if that fixes the ```fontsize``` functionality.

**Comment by whpldgs** [comment] 2022-08-16 01:39
Thank you! 
Use the command "pip install proplot", still install an old version proplot.
To install a development version of proplot, can resolove this issue.

**Closed** 2023-03-28 23:55 UTC
Labels: duplicate
